# AUTO-GERADO: fix_521_tls_spa_v7

server {
  listen 80;
  server_name api.autoatendeai.com.br;
  include /etc/nginx/conf.d/autoatende-acme-location.inc; # __AUTOATENDE_TLS_SAN_WEBROOT_STAGING_PREFLIGHT_V20_C1_TLS_B1_R4__
    location / {
      return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name api.autoatendeai.com.br;
  include /etc/nginx/conf.d/autoatende-acme-location.inc; # __AUTOATENDE_TLS_SAN_WEBROOT_STAGING_PREFLIGHT_V20_C1_TLS_B1_R4__

  ssl_certificate     /etc/nginx/conf.d/tls.crt;
  ssl_certificate_key /etc/nginx/conf.d/tls.key;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://whatsapp-api:3000;
  }
}
